{
 "title": "DevOpsDashboardExec",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "GroupName",
    "label": "GroupName",
    "query": "SELECT DISTINCT group_Name FROM devopsdata.CI_Metrics\nORDER BY group_Name;"
   },
   {
    "name": "AreaName",
    "label": "AreaName",
    "query": "SELECT DISTINCT area_Name FROM devopsdata.CI_Metrics WHERE group_Name IN ($GroupName) ORDER BY area_Name;"
   },
   {
    "name": "ServiceName",
    "label": "ServiceName",
    "query": "SELECT DISTINCT service_Name FROM devopsdata.CI_Metrics WHERE area_Name IN ($AreaName) ORDER BY service_Name;"
   }
  ]
 },
 "panels": [
  {
   "title": "Deployment Frequency",
   "type": "barchart",
   "description": " How often we release to production",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "devopsdatabase",
     "rawSql": "SELECT\r\n  DATEADD(WEEK, DATEDIFF(WEEK, 0, cdt.cd_date), 0) AS WeekStart,\r\n  COUNT(*) AS ProdDeployments\r\nFROM devopsdata.CDT_Metrics cdt\r\nJOIN devopsdata.CI_Metrics ci ON cdt.artifact_id = ci.artifact_id\r\nWHERE\r\n  cdt.env_level = 'PROD'\r\n  AND ci.ci_date BETWEEN $__timeFrom() AND $__timeTo()\r\n  AND cdt.deployment_status = 'SUCCESS'\r\n  AND (ci.group_name IN ($GroupName))\r\n  AND (ci.area_name IN ($AreaName))\r\n  AND (ci.service_name IN ($ServiceName))\r\nGROUP BY DATEADD(WEEK, DATEDIFF(WEEK, 0, cdt.cd_date), 0)\r\nORDER BY WeekStart;"
    }
   ]
  },
  {
   "title": "Delivery Frequency",
   "type": "barchart",
   "description": " How often we release to QA",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "devopsdatabase",
     "rawSql": "SELECT\r\n  DATEADD(WEEK, DATEDIFF(WEEK, 0, cdt.cd_date), 0) AS WeekStart,\r\n  COUNT(*) AS QADeployments\r\nFROM devopsdata.CDT_Metrics cdt\r\nJOIN devopsdata.CI_Metrics ci ON cdt.artifact_id = ci.artifact_id\r\nWHERE\r\n  cdt.env_level = 'QA'\r\n  AND ci.ci_date BETWEEN $__timeFrom() AND $__timeTo()\r\n  AND cdt.deployment_status = 'SUCCESS'\r\n  AND (ci.group_name IN ($GroupName))\r\n  AND (ci.area_name IN ($AreaName))\r\n  AND (ci.service_name IN ($ServiceName))\r\nGROUP BY DATEADD(WEEK, DATEDIFF(WEEK, 0, cdt.cd_date), 0)\r\nORDER BY WeekStart;"
    }
   ]
  },
  {
   "title": "Build Success Rate",
   "type": "timeseries",
   "description": " % of successful builds vs total builds",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "devopsdatabase",
     "rawSql": "SELECT\r\n  DATEADD(WEEK, DATEDIFF(WEEK, 0, ci.ci_date), 0) AS WeekStart,\r\n  CAST(\r\n    100.0 * SUM(CASE WHEN ci.pipeline_status = 'SUCCESS' THEN 1 ELSE 0 END)\r\n    / NULLIF(COUNT(*), 0)\r\n    AS DECIMAL(5,2)\r\n  ) AS WeeklySuccessRate\r\nFROM devopsdata.CI_Metrics ci\r\nWHERE\r\n  ci.ci_date BETWEEN $__timeFrom() AND $__timeTo()\r\n  AND (ci.group_name IN ($GroupName))\r\n  AND (ci.area_name IN ($AreaName))\r\n  AND (ci.service_name IN ($ServiceName))\r\nGROUP BY DATEADD(WEEK, DATEDIFF(WEEK, 0, ci.ci_date), 0)\r\nORDER BY WeekStart;"
    }
   ]
  },
  {
   "title": "Build Duration",
   "type": "barchart",
   "description": "Average CI pipeline duration",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dataset": "devopsdatabase",
     "rawSql": "SELECT\r\n  DATEADD(WEEK, DATEDIFF(WEEK, 0, ci.ci_date), 0) AS WeekStart,\r\n  CAST(AVG(ci.pipeline_duration) AS DECIMAL(10,2)) AS AvgPipelineDuration\r\nFROM devopsdata.CI_Metrics ci\r\nWHERE\r\n  ci.pipeline_duration IS NOT NULL\r\n  AND ci.ci_date BETWEEN $__timeFrom() AND $__timeTo()\r\n  AND (ci.group_name IN ($GroupName))\r\n  AND (ci.area_name IN ($AreaName))\r\n  AND (ci.service_name IN ($ServiceName))\r\nGROUP BY DATEADD(WEEK, DATEDIFF(WEEK, 0, ci.ci_date), 0)\r\nORDER BY WeekStart;"
    }
   ]
  },
  {
   "title": "QA Coverage",
   "type": "timeseries",
   "description": "Average % of code covered by tests",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "devopsdatabase",
     "rawSql": "SELECT\r\n  DATEADD(WEEK, DATEDIFF(WEEK, 0, cdt.cd_date), 0) AS WeekStart,\r\n  CAST(AVG(cdt.code_coverage) AS DECIMAL(5,2)) AS AvgCodeCoveragePercent\r\nFROM devopsdata.CDT_Metrics cdt\r\nJOIN devopsdata.CI_Metrics ci ON cdt.artifact_id = ci.artifact_id\r\nWHERE\r\n  cdt.code_coverage IS NOT NULL\r\n  AND cdt.cd_date BETWEEN $__timeFrom() AND $__timeTo()\r\n  AND (ci.group_name IN ($GroupName))\r\n  AND (ci.area_name IN ($AreaName))\r\n  AND (ci.service_name IN ($ServiceName))\r\nGROUP BY DATEADD(WEEK, DATEDIFF(WEEK, 0, cdt.cd_date), 0)\r\nORDER BY WeekStart;"
    }
   ]
  },
  {
   "title": "Test Pass Rate",
   "type": "timeseries",
   "description": "Test Pass Rate = (passed_tests / total_tests) * 100 \n",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "devopsdatabase",
     "rawSql": "SELECT\r\n  DATEADD(WEEK, DATEDIFF(WEEK, 0, cdt.cd_date), 0) AS WeekStart,\r\n  CAST(\r\n    AVG(\r\n      CASE \r\n        WHEN cdt.total_tests > 0 THEN \r\n          100.0 * cdt.passed_tests / cdt.total_tests\r\n        ELSE NULL\r\n      END\r\n    ) AS DECIMAL(5,2)\r\n  ) AS AvgTestPassRate\r\nFROM devopsdata.CDT_Metrics cdt\r\nJOIN devopsdata.CI_Metrics ci ON cdt.artifact_id = ci.artifact_id\r\nWHERE\r\n  cdt.cd_date BETWEEN $__timeFrom() AND $__timeTo()\r\n  AND (ci.group_name IN ($GroupName))\r\n  AND (ci.area_name IN ($AreaName))\r\n  AND (ci.service_name IN ($ServiceName))\r\nGROUP BY DATEADD(WEEK, DATEDIFF(WEEK, 0, cdt.cd_date), 0)\r\nORDER BY WeekStart;"
    }
   ]
  },
  {
   "title": "Pipeline Throughput",
   "type": "barchart",
   "description": "Number of successful deployments over time",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dataset": "devopsdatabase",
     "rawSql": "SELECT\r\n  DATEADD(WEEK, DATEDIFF(WEEK, 0, cdt.cd_date), 0) AS WeekStart,\r\n  COUNT(*) AS SuccessfulDeployments\r\nFROM devopsdata.CDT_Metrics cdt\r\nJOIN devopsdata.CI_Metrics ci ON cdt.artifact_id = ci.artifact_id\r\nWHERE\r\n  cdt.env_level = 'PROD'\r\n  AND cdt.deployment_status = 'SUCCESS'\r\n  AND cdt.cd_date BETWEEN $__timeFrom() AND $__timeTo()\r\n  AND (ci.group_name IN ($GroupName))\r\n  AND (ci.area_name IN ($AreaName))\r\n  AND (ci.service_name IN ($ServiceName))\r\nGROUP BY DATEADD(WEEK, DATEDIFF(WEEK, 0, cdt.cd_date), 0)\r\nORDER BY WeekStart;"
    }
   ]
  },
  {
   "title": "Artifact Promotion Rate",
   "type": "timeseries",
   "description": "% of builds promoted from dev → qa → prod",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "devopsdatabase",
     "rawSql": "WITH ArtifactPromotionFlags AS (\r\n  SELECT\r\n    cdt.artifact_id,\r\n    DATEADD(WEEK, DATEDIFF(WEEK, 0, MIN(cdt.cd_date)), 0) AS WeekStart,\r\n    MAX(CASE WHEN cdt.env_level = 'DEV' AND cdt.deployment_status = 'SUCCESS' THEN 1 ELSE 0 END) AS has_dev,\r\n    MAX(CASE WHEN cdt.env_level = 'QA' AND cdt.deployment_status = 'SUCCESS' THEN 1 ELSE 0 END) AS has_staging,\r\n    MAX(CASE WHEN cdt.env_level = 'PROD' AND cdt.deployment_status = 'SUCCESS' THEN 1 ELSE 0 END) AS has_prod\r\n  FROM devopsdata.CDT_Metrics cdt\r\n  JOIN devopsdata.CI_Metrics ci ON cdt.artifact_id = ci.artifact_id\r\n  WHERE\r\n    cdt.cd_date BETWEEN $__timeFrom() AND $__timeTo()\r\n  AND (ci.group_name IN ($GroupName))\r\n  AND (ci.area_name IN ($AreaName))\r\n  AND (ci.service_name IN ($ServiceName))\r\n  GROUP BY cdt.artifact_id\r\n)\r\n\r\nSELECT\r\n  WeekStart,\r\n  COUNT(*) AS TotalArtifactsInDev,\r\n  SUM(CASE WHEN has_dev = 1 AND has_staging = 1 AND has_prod = 1 THEN 1 ELSE 0 END) AS FullyPromotedArtifacts,\r\n  CAST(\r\n    100.0 * SUM(CASE WHEN has_dev = 1 AND has_staging = 1 AND has_prod = 1 THEN 1 ELSE 0 END)\r\n    / NULLIF(COUNT(*), 0)\r\n    AS DECIMAL(5,2)\r\n  ) AS ArtifactPromotionRate\r\nFROM ArtifactPromotionFlags\r\nWHERE has_dev = 1\r\nGROUP BY WeekStart\r\nORDER BY WeekStart;"
    }
   ]
  },
  {
   "title": "Rollback Frequency",
   "type": "barchart",
   "description": "Count of rollback deployments",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dataset": "devopsdatabase",
     "rawSql": "SELECT\r\n  DATEADD(WEEK, DATEDIFF(WEEK, 0, cdt.cd_date), 0) AS WeekStart,\r\n  COUNT(*) AS RollbackCount\r\nFROM devopsdata.CDT_Metrics cdt\r\nJOIN devopsdata.CI_Metrics ci ON cdt.artifact_id = ci.artifact_id\r\nWHERE\r\n  cdt.deployment_status = 'ROLLBACK'\r\n  AND cdt.cd_date BETWEEN $__timeFrom() AND $__timeTo()\r\n  AND (ci.group_name IN ($GroupName))\r\n  AND (ci.area_name IN ($AreaName))\r\n  AND (ci.service_name IN ($ServiceName))\r\nGROUP BY DATEADD(WEEK, DATEDIFF(WEEK, 0, cdt.cd_date), 0)\r\nORDER BY WeekStart;"
    }
   ]
  },
  {
   "title": "Test Efficiency",
   "type": "barchart",
   "description": "Average test execution time",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dataset": "devopsdatabase",
     "rawSql": "SELECT\r\n  DATEADD(WEEK, DATEDIFF(WEEK, 0, cdt.cd_date), 0) AS WeekStart,\r\n  CAST(AVG(cdt.test_duration) AS DECIMAL(10,2)) AS AvgTestExecutionTime\r\nFROM devopsdata.CDT_Metrics cdt\r\nJOIN devopsdata.CI_Metrics ci ON cdt.artifact_id = ci.artifact_id\r\nWHERE\r\n  cdt.test_duration IS NOT NULL\r\n  AND cdt.cd_date IS NOT NULL\r\n  AND cdt.cd_date BETWEEN $__timeFrom() AND $__timeTo()\r\n  AND (ci.group_name IN ($GroupName))\r\n  AND (ci.area_name IN ($AreaName))\r\n  AND (ci.service_name IN ($ServiceName))\r\nGROUP BY DATEADD(WEEK, DATEDIFF(WEEK, 0, cdt.cd_date), 0)\r\nORDER BY WeekStart;"
    }
   ]
  }
 ]
}