{
 "title": "DevOpsDashboard0.22",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "GroupName",
    "label": "GroupName",
    "query": "SELECT DISTINCT group_Name FROM devopsdata.CI_Metrics\nORDER BY group_Name;"
   },
   {
    "name": "AreaName",
    "label": "AreaName",
    "query": "SELECT DISTINCT area_Name FROM devopsdata.CI_Metrics WHERE group_Name IN ('$GroupName') ORDER BY area_Name;"
   },
   {
    "name": "ServiceName",
    "label": "ServiceName",
    "query": "SELECT DISTINCT service_Name FROM devopsdata.CI_Metrics WHERE area_Name IN ('$AreaName') ORDER BY service_Name;"
   },
   {
    "name": "ArtifactId",
    "label": "ArtifactId",
    "query": "SELECT DISTINCT artifact_id FROM devopsdata.CI_Metrics WHERE service_Name IN ('$ServiceName') ORDER BY artifact_id;"
   }
  ]
 },
 "panels": [
  {
   "title": "Build & Unit Test Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Build Information",
     "type": "table",
     "description": "Build Information",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "dataset": "devopsdatabase",
       "rawSql": "SELECT\r\n  ci.build_id AS Build#,\r\n  ci.branch_Name AS BranchName,\r\n  ci.artifact_id AS Artifact#,\r\n  ci.action_Type AS Action,\r\n  ci.tests AS TotalUnitTests,\r\n  ci.test_errors AS TestErrors,\r\n  ci.test_failures AS TestFailures,\r\n  ci.skipped_tests AS SkippedTests,\r\n  ci.test_execution_time AS TestExecTime,\r\n  ci.test_success_density AS TestSuccessDensity,\r\n  ci.ci_date AS Date,\r\n  ci.pipeline_status AS Pipeline_Status,\r\n  ci.pipeline_duration AS Pipeline_Duration  \r\nFROM devopsdata.CI_Metrics ci\r\nWHERE\r\n  ci.ci_date BETWEEN $__timeFrom() AND $__timeTo()\r\n\tAND service_Name = '$ServiceName'\r\n\tAND artifact_id IN ($ArtifactId)\r\n\tAND ci_date IS NOT NULL\r\nORDER BY ci.ci_date DESC;\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Application & Code Quality Insights",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Code Coverage - by Unit Tests",
     "type": "timeseries",
     "description": "Code Coverage - by Unit Tests",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "dataset": "devopsdatabase",
       "rawSql": "SELECT\r\n  CAST(ci_date AS DATE) AS time,\r\n  AVG(coverage) AS Coverage,\r\n  AVG(new_coverage) AS NewCodeCoverage,\r\n  AVG(lines_to_cover) AS LinesToCover,\r\n  AVG(new_uncovered_lines) AS NewUnCoveredLines,\r\n  AVG(uncovered_lines) AS UnCoveredLines,\r\n  AVG(new_lines_to_cover) AS NewLinesToCover\r\nFROM devopsdata.CI_Metrics\r\nWHERE \r\nservice_Name = '$ServiceName'\r\nAND artifact_id IN ($ArtifactId)\r\nAND ci_date IS NOT NULL\r\nGROUP BY CAST(ci_date AS DATE)\r\nORDER BY time;"
      }
     ]
    },
    {
     "title": "Code Duplications",
     "type": "timeseries",
     "description": "Code Duplications",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "dataset": "devopsdatabase",
       "rawSql": "SELECT\r\n  CAST(ci_date AS DATE) AS time,\r\n  AVG(duplicated_lines) AS DulicateLines,\r\n  AVG(duplicated_blocks) AS DuplicatedBlocks,\r\n  AVG(new_duplicated_blocks) AS NewDuplicatedBlocks,\r\n  AVG(duplicated_lines_density) AS DuplicatedLinesDensity,\r\n  AVG(new_duplicated_lines_density) AS NewDuplicatedLinesDensity,\r\n  AVG(duplicated_files) AS DuplicatedFiles\r\nFROM devopsdata.CI_Metrics\r\nWHERE \r\nservice_Name = '$ServiceName'\r\nAND artifact_id IN ($ArtifactId)\r\nAND ci_date IS NOT NULL\r\nGROUP BY CAST(ci_date AS DATE)\r\nORDER BY time;"
      }
     ]
    },
    {
     "title": "Application Issues",
     "type": "timeseries",
     "description": "Application Issues",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "dataset": "devopsdatabase",
       "rawSql": "SELECT\r\n  CAST(ci_date AS DATE) AS time,\r\n  AVG(violations) AS TotalIssues,\r\n  AVG(new_violations) AS NewCodeIssues,\r\n  AVG(open_issues) AS OpenIssues,\r\n  AVG(accepted_issues) AS AcceptedIssues,\r\n  AVG(false_positive_issues) AS FalsePositiveIssues\r\nFROM devopsdata.CI_Metrics\r\nWHERE \r\nservice_Name = '$ServiceName'\r\nAND artifact_id IN ($ArtifactId)\r\nAND ci_date IS NOT NULL\r\nGROUP BY CAST(ci_date AS DATE)\r\nORDER BY time;"
      }
     ]
    },
    {
     "title": "Software Quality Maintainability Metrics",
     "type": "timeseries",
     "description": "Software Quality Maintainability Metrics",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "targets": [
      {
       "dataset": "devopsdatabase",
       "rawSql": "SELECT\r\n  CAST(ci_date AS DATE) AS time,\r\n  AVG(sqm_issues) AS Issues,\r\n  AVG(new_sqm_issues) AS NewIssues\r\nFROM devopsdata.CI_Metrics\r\nWHERE \r\nservice_Name = '$ServiceName'\r\nAND artifact_id IN ($ArtifactId)\r\nAND ci_date IS NOT NULL\r\nGROUP BY CAST(ci_date AS DATE)\r\nORDER BY time;\r\n"
      }
     ]
    },
    {
     "title": "Application Size",
     "type": "timeseries",
     "description": "Application Size",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "targets": [
      {
       "dataset": "devopsdatabase",
       "rawSql": "SELECT\r\n  CAST(ci_date AS DATE) AS time,\r\n  AVG(ncloc) AS TotalLines,\r\n  AVG(statements) AS Statements,\r\n  AVG(functions) AS Functions,\r\n  AVG(classes) AS Classes,\r\n  AVG(files) AS Files,\r\n  AVG(comment_lines) AS CommentedLines,\r\n  AVG(comment_lines_density) AS CommentLinesDensity\r\nFROM devopsdata.CI_Metrics\r\nWHERE \r\nservice_Name = '$ServiceName'\r\nAND artifact_id IN ($ArtifactId)\r\nAND ci_date IS NOT NULL\r\nGROUP BY CAST(ci_date AS DATE)\r\nORDER BY time;"
      }
     ]
    },
    {
     "title": "Application Complexity",
     "type": "timeseries",
     "description": "Application Complexity",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "targets": [
      {
       "dataset": "devopsdatabase",
       "rawSql": "SELECT\r\n  CAST(ci_date AS DATE) AS time,\r\n  AVG(complexity) AS Complexity,\r\n  AVG(cognitive_complexity) AS CognitiveComplexity\r\nFROM devopsdata.CI_Metrics\r\nWHERE \r\nservice_Name = '$ServiceName'\r\nAND artifact_id IN ($ArtifactId)\r\nAND ci_date IS NOT NULL\r\nGROUP BY CAST(ci_date AS DATE)\r\nORDER BY time;"
      }
     ]
    }
   ]
  },
  {
   "title": "Application Security Scan Trends",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "SAST Score Trends",
     "type": "timeseries",
     "description": "CheckMarx SAST Score Trends ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "dataset": "devopsdatabase",
       "rawSql": "SELECT\r\n  CAST(ci_date AS DATE) AS time,\r\n  AVG(sast_issue_total) AS Total,\r\n  AVG(sast_issue_blocker) AS Blocker,\r\n  AVG(sast_issue_critical) AS Critcal,\r\n  AVG(sast_issue_high) AS High,\r\n  AVG(sast_issue_medium) AS Medium,\r\n  AVG(sast_issue_low) AS low\r\nFROM devopsdata.CI_Metrics\r\nWHERE \r\nservice_Name = '$ServiceName'\r\nAND artifact_id IN ($ArtifactId)\r\nAND ci_date IS NOT NULL\r\nGROUP BY CAST(ci_date AS DATE)\r\nORDER BY time;"
      }
     ]
    },
    {
     "title": "SCA Score Trends",
     "type": "timeseries",
     "description": "CheckMarx SCAScore Trends ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "dataset": "devopsdatabase",
       "rawSql": "SELECT\r\n  CAST(ci_date AS DATE) AS time,\r\n  AVG(sca_issue_total) AS Total,\r\n  AVG(sca_issue_blocker) AS Blocker,\r\n  AVG(sca_issue_critical) AS Critcal,\r\n  AVG(sca_issue_high) AS High,\r\n  AVG(sca_issue_medium) AS Medium,\r\n  AVG(sca_issue_low) AS low\r\nFROM devopsdata.CI_Metrics\r\nWHERE \r\nservice_Name = '$ServiceName'\r\nAND artifact_id IN ($ArtifactId)\r\nAND ci_date IS NOT NULL\r\nGROUP BY CAST(ci_date AS DATE)\r\nORDER BY time;"
      }
     ]
    },
    {
     "title": "TwistLock Vulnerabilities Score Trends",
     "type": "timeseries",
     "description": "Twistlock Vulnerabilities Trends ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "dataset": "devopsdatabase",
       "rawSql": "SELECT\r\n  CAST(ci_date AS DATE) AS time,\r\n  AVG(twist_vulnerabilities_total) AS Total,\r\n  AVG(twist_vulnerabilities_blocker) AS Blocker,\r\n  AVG(twist_vulnerabilities_critical) AS Critcal,\r\n  AVG(twist_vulnerabilities_high) AS High,\r\n  AVG(twist_vulnerabilities_medium) AS Medium,\r\n  AVG(twist_vulnerabilities_low) AS low\r\nFROM devopsdata.CI_Metrics\r\nWHERE \r\nservice_Name = '$ServiceName'\r\nAND artifact_id IN ($ArtifactId)\r\nAND ci_date IS NOT NULL\r\nGROUP BY CAST(ci_date AS DATE)\r\nORDER BY time;\r\n"
      }
     ]
    },
    {
     "title": "Twistlock Compliance Score Trends",
     "type": "timeseries",
     "description": "Twistlock Compliance Trends",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "dataset": "devopsdatabase",
       "rawSql": "SELECT\r\n  CAST(ci_date AS DATE) AS time,\r\n  AVG(twist_compliance_total) AS Total,\r\n  AVG(twist_compliance_blocker) AS Blocker,\r\n  AVG(twist_compliance_critical) AS Critcal,\r\n  AVG(twist_compliance_high) AS High,\r\n  AVG(twist_compliance_medium) AS Medium,\r\n  AVG(twist_compliance_low) AS low\r\nFROM devopsdata.CI_Metrics\r\nWHERE \r\nservice_Name = '$ServiceName'\r\nAND artifact_id IN ($ArtifactId)\r\nAND ci_date IS NOT NULL\r\nGROUP BY CAST(ci_date AS DATE)\r\nORDER BY time;"
      }
     ]
    }
   ]
  },
  {
   "title": "Quality Assurance Insights",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Deployment & QA Details",
     "type": "table",
     "description": "Deployment & QA Details",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "dataset": "devopsdatabase",
       "rawSql": "SELECT\r\n  cd.build_id AS Build#,\r\n  ci.service_Name AS Service_Name,\r\n  cd.started_by AS StartedBy,\r\n  cd.approver AS Approver,\r\n  cd.artifact_id AS Artifact#,\r\n  cd.action_Type AS Action,\r\n  cd.cd_date AS DeploymentDate,\r\n  cd.env_level AS EnvLevel,\r\n  cd.deployment_status AS DeploymentStatus,\r\n  cd.total_tests AS TotalTests#,\r\n  cd.passed_tests AS PassedTests,\r\n  cd.failed_tests AS FailedTests,\r\n  cd.notrun_tests AS NotRunTests,\r\n  cd.tests_status AS TestsStatus,\r\n  cd.tests_coverage AS QACoverage,\r\n  cd.test_duration AS TestDuration,\r\n  cd.test_tool AS TestingTool,\r\n  cd.pipeline_status AS PipelineStatus,\r\n  cd.pipeline_duration AS ExecutionDuration  \r\nFROM devopsdata.CDT_Metrics cd\r\nJOIN devopsdata.CI_Metrics ci ON cd.artifact_id = ci.artifact_id\r\nWHERE\r\n    cd.cd_date BETWEEN $__timeFrom() AND $__timeTo()\r\n\tAND ci.service_Name = '$ServiceName'\r\n\tAND ci.artifact_id IN ($ArtifactId)\r\n\tAND cd_date IS NOT NULL\r\nORDER BY cd.cd_date DESC;"
      }
     ]
    }
   ]
  }
 ]
}